### PR TITLE
Added an description.

### PR DESCRIPTION
**Pull request by AraHaan**
Added an description to readme.

### CODE REVIEW

**Review by jchristgit — APPROVED** [review]

**Comment by wubbalubbadubdubonline** [comment]
i honestly thought that it had been merged already

**Comment by AraHaan** [comment]
oh the other branches you might want to do an ``git pull origin master`` followed by an ``git push`` to update the descriptions on all of them.

**Comment by jchristgit** [comment]
i can't merge to master

**Comment by AraHaan** [comment]
hmm I see, so it means you would have to figure out an cherry pick.

**Comment by jchristgit** [comment]
what is a cherry pick

**Comment by AraHaan** [comment]
see ``git cherry-pick``

```git cherrypick
git: 'cherrypick' is not a git command. See 'git --help'.

Did you mean this?
        cherry-pick

git cherry-pick
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by AraHaan** [comment]
The help from ``git cherry-pick`` when in an ``.git`` repo:

```
git cherry-pick
usage: git cherry-pick [<options>] <commit-ish>...
   or: git cherry-pick <subcommand>

    --quit                end revert or cherry-pick sequence
    --continue            resume revert or cherry-pick sequence
    --abort               cancel revert or cherry-pick sequence
    -n, --no-commit       don't automatically commit
    -e, --edit            edit the commit message
    -s, --signoff         add Signed-off-by:
    -m, --mainline <n>    parent number
    --rerere-autoupdate   update the index with reused conflict resolution if po
ssible
    --strategy <strategy>
                          merge strategy
    -X, --strategy-option <option>
                          option for merge strategy
    -S, --gpg-sign[=<key-id>]
                          GPG sign commit
    -x                    append commit name
    --ff                  allow fast-forward
    --allow-empty         preserve initially empty commits
    --allow-empty-message
                          allow commits with empty messages
    --keep-redundant-commits
                          keep redundant, empty commits
```

**Pull request merged**
